# id used to name lockfile and as the default for the logfile and excludes
# files
id: my_backup

# File or list of files to pass to rsync's --exclude-from. Listed items can
# either be paths to files or the names of files in the same directory as the
# yaml config file. If the file (id).xcl exists in the same directory as the
# yaml config file, it is also used.
excludes: /path/to/excludes.xcl

# Lockfile path. Overrides the default path of id.lck (with id from above) in
# the folder with the config file
# lockfile: /path/to/lockfile

# Logfile settings
# (Other than path, the values given below are the defaults. None of values
# need to be specified).
# path: path to logfile to use. Defaults to id.log in the working directory
# backup_count: number of rotated log files to keep (0 keeps all logs)
# max_bytes: maximum size in bytes of log file before it is rotated (0 never
#   rotates)
# copy_to_dest: log file copied to remote destination if true
# mode: file mode for logfile ('a' to append, 'w' to overwrite)
logfile:
    path: /path/to/logfile.log
    max_bytes: 1e6
    backup_count: 5
    mode: 'a'
    copy_to_dest: False

# remote settings
# Omit these settings to backup between local directories
#
# location can be 'src', 'dest', or 'none'
# host should be a host recognizeable by ssh
#
# remote:
#     location: dest
#     host: user@host

# List of paths to use as rsync SRC arguments
sources:
- /path/to/first/backup
- /path/to/second/backup

# Target to pass as the rsync DEST argument.
destination: /some/target/path

# Options to pass to the rsync command used to backup the files. The options
# given below are the defaults and do not need to be specified. Options can be
# removed by prefixing them with "no", e.g. "no--stats".
#
# Note that the chmod option is necessary for old backups to be linked against
# and pruned.
rsync_opts:
- --archive
- --delete
- -hhh
- --stats
- --chmod=u+rw
# For remote:
# - --compress

# aging_params -- how to prune old backups
# 
# A list of pairs of numbers. The first number is the spacing to use between
# retained backups and the second number is the oldest backups can be for this
# spacing to be applied. You want the spacings to get wider as the backups get
# older. All of the numbers are in days. The values below are the defaults.
#
# aging_params:
# - [0.5/24, 2]
# - [1, 14]
# - [7, 60]
# - [30, 730]
# - [365, -1]
